services:
  database:
    image: postgres:16
    container_name: sandbox-db
    hostname: sandbox-db
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - ./docker/init-database:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123

volumes:
  postgres-data:
